name: rebel-stream
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch=2.0.0
  - cudatoolkit=11.8  # Comment out for CPU-only installation
  - pandas>=2.0.0
  - pip:
      - transformers>=4.34.0
      - tqdm>=4.65.0
      - nltk>=3.8.1
      - langdetect>=1.0.9
      - watchdog>=3.0.0
      - pytest>=7.4.0
      - pytest-asyncio>=0.21.0
      - pytest-cov>=4.1.0
      - black>=23.3.0
      - isort>=5.12.0
      - flake8>=6.0.0
      - mypy>=1.3.0
      - mkdocs>=1.4.3
      - mkdocs-material>=9.1.15
      - python-dotenv>=1.0.0
      - typing-extensions>=4.5.0
      - colorama>=0.4.6
variables:
  PYTORCH_CUDA_ALLOC_CONF: max_split_size_mb:512